services:
  astro:
    build:
      context: .
    container_name: astro-app
    restart: unless-stopped
    environment:
      PUBLIC_WS_QUEUE_URL: wss://queue:3000
    ports:
      - "4321:4321"

  
  queue:
    build:
      context: ./ws
    container_name: queue
    restart: unless-stopped
    ports:
      - "3000:3000"
